### ISSUE TITLE
Publish sourcemaps

### ISSUE THREAD

**Issue by MiguelMadero** [square/lgtm#18]
The bower dist assets have a reference to the sourcemap, but the `.map` files aren't published. Running `make dist` generates this ones correctly, but we don't include them. 

Any chance we can bump to 1.0.5 in bower and include the maps? Alternatively, we could drop the sourcemap tag instead. This will help reduce the noise in tools (like ember-cli that complains if the sourcemap isn't found) or Chrome devtools that will get a 404. 

This is low priority, nothing breaks, but it just creates unnecessary noise.

**Comment by tmquinn** [comment]
This is also driving me crazy. I am seriously contemplating giving up programming and becoming a sherpa if this minor annoyance is not corrected...

**Comment by MiguelMadero** [comment]
Thanks for fixing this!
