### ISSUE TITLE
[Feature Request] Validations on a nested object.

### ISSUE THREAD

**Issue by pselden** [square/lgtm#9]
Is it possible to run validations on a nested object?

For instance.

```javascript
var paymentInfo = {
   creditCard: {
     number: 45343434343,
     expiration: '01/15'
   }
};

var validator = LGTM.validator()
   .validates('creditCard.number').required('Credit card number is required')
.build();

validator.validate(paymentInfo).then(function() {/*... */);
```
If not, is there a way to do something like this or do I have to build validations for each part separately and combine the results?

**Comment by eventualbuddha** [comment]
Closing as inactive.

**Comment by ianwalter** [comment]
@pselden Did you find a work around for this? Your second example looks ideal.
